### PR TITLE
Cli tests

### PR DESCRIPTION
**Pull request by tomalec**
This is as far as I get with making Travis and CLI tests work.

We still fail on Shadow DOM API with jsdom.

@warpech please take a look

### CODE REVIEW

**Comment by warpech** [comment]
It does not run for me:

```
C:\www\PuppetJs>npm test

> puppetjs@2.2.0 test C:\www\PuppetJs
> jasmine JASMINE_CONFIG_PATH=test/jasmine.json

Started
FFFFFFFFFC:\www\PuppetJs\test\spec\dom\LinksSpec.js:47
    div.createShadowRoot().appendChild(a);
        ^

TypeError: div.createShadowRoot is not a function
    at createLinkTestNestedShadowDOM (C:\www\PuppetJs\test\spec\dom\LinksSpec.js
:47:9)
    at null._onTimeout (C:\www\PuppetJs\test\spec\dom\LinksSpec.js:106:11)
    at Timer.listOnTimeout (timers.js:92:15)
 npm ERR! Test failed.  See above for more details.
```

Node v4.4.4

Can you update README.md with information how to run the CLI tests?

**Comment by warpech** [comment]
I have the same problem with v6.9.1

**Comment by tomalec** [comment]
That's what I meant by "We still fail on Shadow DOM API with jsdom."

CLI test does not run, as there is no node environment that works with webcomponents.js (Shadow DOM)at least none I'm aware of.

So we will either 
1. move to mocha+selenium (WCT),
2. remove Shadow DOM tests,
3. Move Shadow DOM tests and related functionality to `puppet-client`,

**Comment by warpech** [comment]
Is there a way to conditionally skip a test if `document.createShadowRoot` is undefined?

**Comment by tomalec** [comment]
I bet there is, but I doubt if in long run somebody will care thet locally in browser test fails if `npm test` and travis are green.

**Comment by warpech** [comment]
I get it...

Can you then just pls add a warning that says that Shadow DOM tests fail because the test suite is not run in a web browser.

**Comment by warpech** [comment]
@tomalec your suggestion is to merge this as is, assuming that our tester in future will figure out how to make this pass in Travis and CLI? (phantomjs comes to mind).

**Comment by tomalec** [comment]
Hm.. I thought I have commented it (maybe in some other repo ;) ), sorry

I managed to run it with phantomjs but is shown that we have tests failing in polyfilled browsers.

I'll merge it as it is. At least we could track the number of failing tests.

**Comment by warpech** [comment]
Merging

**Pull request merged**
